name: DÃ©ploiement Django vers la VM

on:
  push:
    branches:
      - main  # DÃ©clenche uniquement sur les pushs vers la branche main

jobs:
  deploy:
    name: DÃ©ployer sur la VM
    runs-on: self-hosted

    steps:
      - name: ðŸ“¥ Cloner le dÃ©pÃ´t
        uses: actions/checkout@v3
      - name: ðŸ§ª VÃ©rifier la variable SSH_HOST
        run: |
          if [ -z "${{ secrets.SSH_HOST }}" ]; then
            echo "âŒ SSH_HOST est vide ou non dÃ©fini" && exit 1
          else
            echo "âœ… SSH_HOST est dÃ©fini ${{ secrets.SSH_HOST }}"
          fi
      - name: ðŸ” DÃ©chiffrer la clÃ© SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_ci
          chmod 600 ~/.ssh/github_ci

      - name: ðŸš€ DÃ©ployer le projet sur la VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github_ci log430@${{ secrets.SSH_HOST }} "
            cd ~/LOG430-01-Labo-02 &&
            git pull &&
            docker-compose down &&
            docker-compose up --build -d
          "

